#!/bin/bash

# The following template provides a comprehensive set of SBATCH parameters 
# to give users better understanding of the cluster resources.
# For the complete information about SBATCH:
# https://slurm.schedmd.com/sbatch.html.

#SBATCH --job-name=rna_fq2bamSRR            # Job name		  # default: script name or sbatch
#SBATCH --ntasks=4                    # Number of tasks		  # default: 1 task per node
#SBATCH --cpus-per-task=10             # Number of CPUs per task	  # default: 1 CPU per task 
#SBATCH --mem=128gb                    # Memory size requested	  # default: 4gb
#SBATCH --time=5:00:00               # Time limit hrs:min:sec	  # default: 01:00:00 (+1 hours of extra overtime limit) 
#SBATCH --output=my_job%j.log           # Output file		  # default: slurm-<jobid>.out
#SBATCH --gres=gpu:3                  # Number of GPUs requested  # default: none (0)
#SBATCH --nodes=1              # Req min-max of nodes      # default: 1-as many as possible to satisfy the job without delay
#SBATCH --partition=batch	      # Req specific partition    # default: batch
#SBATCH --export=ALL		      # Pass the env var

export PB_PATH=/shared/parabrick/parabricks
export PATH=$PB_PATH:$PATH
export PB_HOME=/shared/parabrick/parabricks

$PB_PATH/pbrun rna_fq2bam --in-fq /home/peerapat.kha/Fastq/SRR10989467_1.fastq /home/peerapat.kha/Fastq/SRR10989467_2.fastq \
--genome-lib-dir /home/peerapat.kha/hg38_st1 \
--output-dir /home/peerapat.kha/testparabrickSRR_3gpu/ \
--out-bam /home/peerapat.kha/testparabrickSRR/testparabrickSRR.bam/ \
--ref /home/peerapat.kha/hg38_st1/hg38.fa

